services:
  postgres:
    container_name: postgres-gs-app
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: game_store_app_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-gsa

networks:
  spring-gsa:
    driver: bridge
volumes:
  postgres:
    driver: local
